import React, { createContext, useContext, useState, useEffect } from 'react';

const TRANSLATIONS = {
  en: {
    app_title: "CivicPulse AI",
    tagline: "Multilingual Citizen Feedback & Infrastructure Intelligence",
    nav_citizen: "Citizen Portal",
    nav_gov: "Gov Dashboard",
    tab_report: "Report Grievance",
    tab_track: "Track Status",
    form_heading: "Submit a Civic Grievance",
    form_subheading: "Voice or text in any language. Our AI converts your report into actionable infrastructure intelligence.",
    demo_presets_title: "Quick-Demo Grievance Scenarios (Click to Pre-fill):",
    name_label: "Your Name (Optional)",
    contact_label: "Phone / Contact (Optional)",
    desc_label: "Describe the Issue",
    desc_placeholder: "Type or speak in Hindi, Marathi, Spanish, English, etc... (e.g. 'Main road water pipe burst near hospital causing flooding')",
    voice_btn_idle: "Speak Issue",
    voice_btn_recording: "Listening... (Click to stop)",
    voice_not_supported: "Speech recognition is not supported in this browser. Please type your grievance.",
    category_label: "Civic Category (Auto-Detected by AI if left blank)",
    location_label: "Pin Location on Map",
    gps_btn: "Use My GPS Location",
    selected_coords: "Selected GPS Coordinates",
    address_label: "Landmark / Street Address",
    address_placeholder: "e.g. Opposite City Hospital Gate 2, Sector 3",
    photo_label: "Attach Photo (Optional)",
    drop_photo: "Click or drag image to upload proof",
    submit_btn: "Submit Grievance with AI Prioritization",
    submitting: "Analyzing with AI Pipeline...",
    tracking_heading: "Track Your Grievance Status",
    tracking_subheading: "Enter your tracking ID (e.g. CP-2026-W101) to view real-time municipal action timeline.",
    tracking_placeholder: "Enter Tracking Code (e.g. CP-2026-W101)",
    track_btn: "Lookup Status",
    loading_status: "Fetching grievance status...",
    status_received: "Received",
    status_investigating: "Investigating",
    status_in_progress: "In Progress",
    status_resolved: "Resolved",
    sla_target: "Target Resolution SLA",
    timeline_title: "Municipal Action & Resolution Timeline",
    no_logs: "No status updates recorded yet.",
    success_title: "Grievance Registered Successfully!",
    tracking_id_label: "Your Unique Tracking ID",
    copy_tracking: "Copy Tracking ID",
    copied: "Copied!",
    ai_analysis_title: "AI Pipeline Intelligence Summary",
    category_detected: "Detected Category",
    severity_level: "Severity Rating",
    priority_score: "Infrastructure Priority Score",
    sla_estimate: "Estimated Resolution SLA",
    duplicate_notice: "Linked to existing spatial hotspot cluster",
  },
  hi: {
    app_title: "सिविकपल्स एआई",
    tagline: "बहुभाषी नागरिक शिकायत एवं सार्वजनिक अवसंरचना इंटेलिजेंस",
    nav_citizen: "नागरिक पोर्टल",
    nav_gov: "प्रशासन डैशबोर्ड",
    tab_report: "शिकायत दर्ज करें",
    tab_track: "स्थिति ट्रैक करें",
    form_heading: "नागरिक शिकायत दर्ज करें",
    form_subheading: "अपनी भाषा में बोलें या लिखें। हमारा AI आपकी रिपोर्ट को प्राथमिकता के आधार पर हल करता है।",
    demo_presets_title: "त्वरित डेमो परिदृश्य (क्लिक करें):",
    name_label: "आपका नाम (वैकल्पिक)",
    contact_label: "फ़ोन / संपर्क (वैकल्पिक)",
    desc_label: "समस्या का विवरण",
    desc_placeholder: "हिंदी, मराठी, अंग्रेजी आदि में लिखें या बोलें (उदा. 'अस्पताल के सामने पानी का पाइप फट गया है')",
    voice_btn_idle: "बोलकर दर्ज करें",
    voice_btn_recording: "सुन रहे हैं... (रोकने के लिए क्लिक करें)",
    voice_not_supported: "इस ब्राउज़र में वॉइस इनपुट समर्थित नहीं है। कृपया टाइप करें।",
    category_label: "नागरिक श्रेणी (खाली छोड़ने पर AI स्वतः चुनेगा)",
    location_label: "मानचित्र पर स्थान चुनें",
    gps_btn: "मेरा वर्तमान स्थान (GPS)",
    selected_coords: "चयनित जीपीएस निर्देशांक",
    address_label: "लैंडमार्क / पता",
    address_placeholder: "उदा. सिटी हॉस्पिटल गेट 2 के सामने, सेक्टर 3",
    photo_label: "फोटो संलग्न करें (वैकल्पिक)",
    drop_photo: "प्रमाण के लिए फोटो अपलोड करें",
    submit_btn: "AI प्राथमिकीकरण के साथ शिकायत भेजें",
    submitting: "AI पाइपलाइन विश्लेषण जारी है...",
    tracking_heading: "शिकायत की स्थिति जांचें",
    tracking_subheading: "वास्तविक समय की प्रगति देखने के लिए अपना ट्रैकिंग कोड दर्ज करें।",
    tracking_placeholder: "ट्रैकिंग कोड दर्ज करें (उदा. CP-2026-W101)",
    track_btn: "स्थिति देखें",
    loading_status: "स्थिति खोजी जा रही है...",
    status_received: "प्राप्त",
    status_investigating: "जांच जारी",
    status_in_progress: "प्रगति पर",
    status_resolved: "निस्तारित",
    sla_target: "लक्षित समाधान समय",
    timeline_title: "विभागीय कार्रवाई और प्रगति टाइमलाइन",
    no_logs: "अभी तक कोई नया अपडेट नहीं।",
    success_title: "शिकायत सफलतापूर्वक दर्ज हुई!",
    tracking_id_label: "आपका ट्रैकिंग कोड",
    copy_tracking: "कोड कॉपी करें",
    copied: "कॉपी हो गया!",
    ai_analysis_title: "AI विश्लेषण सारांश",
    category_detected: "पहचानी गई श्रेणी",
    severity_level: "गंभीरता स्तर",
    priority_score: "इन्फ्रास्ट्रक्चर प्राथमिकता स्कोर",
    sla_estimate: "अनुमानित समाधान समय",
    duplicate_notice: "मौजूदा हॉटस्पॉट क्लस्टर से लिंक किया गया",
  },
  mr: {
    app_title: "सिव्हिकपल्स AI",
    tagline: "बहुभाषिक नागरिक तक्रार आणि पायाभूत सुविधा बुद्धिमत्ता",
    nav_citizen: "नागरिक पोर्टल",
    nav_gov: "प्रशासन डॅशबोर्ड",
    tab_report: "तक्रार नोंदवा",
    tab_track: "स्थिती ट्रॅक करा",
    form_heading: "नागरी तक्रार नोंदवा",
    form_subheading: "मराठी, हिंदी किंवा इंग्रजीत बोला किंवा लिहा. AI द्वारे समस्येचे त्वरित वर्गीकरण व प्राधान्य.",
    demo_presets_title: "डेमो तक्रार उदाहरणे (क्लिक करा):",
    name_label: "आपले नाव (ऐच्छिक)",
    contact_label: "संपर्क क्रमांक (ऐच्छिक)",
    desc_label: "तक्रारीचे वर्णन",
    desc_placeholder: "मराठीत बोला किंवा टाईप करा (उदा. 'रस्त्यावर मोठा खड्डा पडला असून तातडीने दुरुस्त करा')",
    voice_btn_idle: "आवाजाने नोंदवा",
    voice_btn_recording: "ऐकत आहे... (थांबवण्यासाठी क्लिक करा)",
    voice_not_supported: "या ब्राउझरमध्ये व्हॉइस इनपुट उपलब्ध नाही.",
    category_label: "तक्रार वर्ग (AI आपोआप ओळखेल)",
    location_label: "नकाशावर जागा निवडा",
    gps_btn: "माझे जीपीएस स्थान",
    selected_coords: "निवडलेले जीपीएस निर्देशांक",
    address_label: "पत्ता / लँडमार्क",
    address_placeholder: "उदा. रुग्णालय चौक, सेक्टर ३",
    photo_label: "फोटो जोडा (ऐच्छिक)",
    drop_photo: "पुरावा म्हणून फोटो अपलोड करा",
    submit_btn: "AI विश्लेषणासह तक्रार सबमिट करा",
    submitting: "AI विश्लेषण सुरू आहे...",
    tracking_heading: "तक्रारीची स्थिती तपासा",
    tracking_subheading: "तक्रार प्रगती पाहण्यासाठी आपला ट्रॅकिंग कोड टाका.",
    tracking_placeholder: "ट्रॅकिंग कोड टाका (उदा. CP-2026-W101)",
    track_btn: "स्थिती शोधा",
    loading_status: "माहिती लोड होत आहे...",
    status_received: "प्राप्त",
    status_investigating: "तपास सुरू",
    status_in_progress: "प्रगतीपथावर",
    status_resolved: "निवारण झाले",
    sla_target: "लक्ष्य वेळ (SLA)",
    timeline_title: "कारवाई आणि निराकरण टाइमलाइन",
    no_logs: "अद्याप कोणतीही नोंद नाही.",
    success_title: "तक्रार यशस्वीरित्या नोंदवली गेली!",
    tracking_id_label: "आपला ट्रॅकिंग आयडी",
    copy_tracking: "आयडी कॉपी करा",
    copied: "कॉपी केले!",
    ai_analysis_title: "AI विश्लेषण निष्कर्ष",
    category_detected: "ओळखलेला विभाग",
    severity_level: "तीव्रता पातळी",
    priority_score: "पायाभूत सुविधा प्राधान्य गुण",
    sla_estimate: "अपेक्षित निराकरण वेळ",
    duplicate_notice: "जवळपासच्या सक्रिय हॉटस्पॉट क्लस्टरशी जोडले गेले",
  },
  es: {
    app_title: "CivicPulse AI",
    tagline: "Comentarios Ciudadanos Multilingües e Inteligencia de Infraestructura",
    nav_citizen: "Portal Ciudadano",
    nav_gov: "Panel de Gobierno",
    tab_report: "Reportar Problema",
    tab_track: "Rastrear Estado",
    form_heading: "Presentar una Queja Cívica",
    form_subheading: "Por voz o texto en cualquier idioma. Nuestra IA prioriza y gestiona las reparaciones de infraestructura pública.",
    demo_presets_title: "Escenarios de Demostración Rápida (Clic para llenar):",
    name_label: "Su Nombre (Opcional)",
    contact_label: "Teléfono / Contacto (Opcional)",
    desc_label: "Descripción del Problema",
    desc_placeholder: "Escriba o hable en español, inglés, etc... (ej. 'Fuga masiva de agua en la avenida principal frente al hospital')",
    voice_btn_idle: "Grabar Voz",
    voice_btn_recording: "Escuchando... (Clic para detener)",
    voice_not_supported: "Reconocimiento de voz no soportado en este navegador.",
    category_label: "Categoría Cívica (IA detectará automáticamente si está vacío)",
    location_label: "Fijar Ubicación en el Mapa",
    gps_btn: "Usar mi GPS",
    selected_coords: "Coordenadas GPS seleccionadas",
    address_label: "Dirección / Punto de Referencia",
    address_placeholder: "ej. Frente a la Puerta 2 del Hospital, Sector 3",
    photo_label: "Adjuntar Foto (Opcional)",
    drop_photo: "Haga clic o arrastre imagen para subir",
    submit_btn: "Enviar Queja con Priorización de IA",
    submitting: "Analizando con IA...",
    tracking_heading: "Rastrear Estado de Queja",
    tracking_subheading: "Ingrese su código de seguimiento para ver el progreso municipal en tiempo real.",
    tracking_placeholder: "Ingrese Código (ej. CP-2026-W101)",
    track_btn: "Consultar Estado",
    loading_status: "Cargando estado...",
    status_received: "Recibido",
    status_investigating: "Investigando",
    status_in_progress: "En Progreso",
    status_resolved: "Resuelto",
    sla_target: "SLA de Resolución Objetivo",
    timeline_title: "Historial de Acción y Resolución",
    no_logs: "Sin registros de actualización.",
    success_title: "¡Queja Registrada Exitosamente!",
    tracking_id_label: "Su Código de Seguimiento",
    copy_tracking: "Copiar Código",
    copied: "¡Copiado!",
    ai_analysis_title: "Resumen de Inteligencia de IA",
    category_detected: "Categoría Detectada",
    severity_level: "Nivel de Gravedad",
    priority_score: "Puntuación de Prioridad",
    sla_estimate: "SLA Estimado de Resolución",
    duplicate_notice: "Vinculado a un grupo de puntos críticos activos",
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [currentLang, setCurrentLang] = useState(() => {
    return localStorage.getItem('civicpulse_lang') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('civicpulse_lang', currentLang);
  }, [currentLang]);

  const t = (key) => {
    const langDict = TRANSLATIONS[currentLang] || TRANSLATIONS.en;
    return langDict[key] || TRANSLATIONS.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ currentLang, setLanguage: setCurrentLang, t, availableLanguages: [
      { code: 'en', label: 'English' },
      { code: 'hi', label: 'हिंदी (Hindi)' },
      { code: 'mr', label: 'मराठी (Marathi)' },
      { code: 'es', label: 'Español (Spanish)' },
    ] }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
